### ISSUE TITLE
Missing pty.h header file on Darwin

### ISSUE THREAD

**Issue by barnumbirr** [dimkr/tty8#1]
Hello there,

Out of curiosity I tried to compile this on OSX and I of course failed miserably. The `pty.h` header file from `GNULib`is missing on Darwin platforms and all the functions therefrom have been implemented in `util.h` as per [this link I found](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/forkpty.3.html).

Is there any chance you could fix this?

Thank you very much.

Cheers.

**Comment by barnumbirr** [comment]
So I've done a bit of digging in the code and found that you're also using `'F_SETSIG'`from `fcntl`which is also not available on Darwin platforms.
Guess this awesome piece of code is really not portable at all.

Sorry for bothering you.

Cheers.

**Comment by dimkr** [comment]
Yeah, I wouldn't expect it to be portable because of the fcntl and tty trickery it does. I can take another look at the subject, though - Screen, tmux, dvtm, etc' work on OS X, after all.

**Comment by barnumbirr** [comment]
I could indeed use `screen`or `tmux`but I've gotten really used to using `tty8`on my Debian servers so I wondered if maybe it would be possible to get it working on Darwin.

Thank you for your time though.

Cheers.
